[tox]
envlist = mypy,py3{11,12,13,14,15},external_tests,coverage

[testenv]
# Install wheels instead of source distributions for faster execution.
package = wheel
# Share the build environment between tox environments.
wheel_build_env = .pkg

dependency_groups =
  coverage
  tests
commands =
  coverage run --parallel-mode -m pytest {posargs:tests}

[testenv:coverage]
dependency_groups = coverage
depends = py3{11,12,13,14,15}
commands =
  coverage combine
  coverage report

[testenv:external_tests]
commands =
  import-linter lint --config tests/.importlinter --verbose --debug

[testenv:mypy]
dependency_groups = mypy
commands =
  mypy {posargs:.}
